//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lim_Circus.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int Animal_ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Gender_ID { get; set; }
        public decimal Weight { get; set; }
        public string Food_Preferences { get; set; }
        public string Care_Recommendations { get; set; }
        public int Tamer_ID { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Users Users { get; set; }
    }
}
